/*******************************************************************************
TouchHook.h - defines the exported functions for the DLL application.

Purpose: Intercepts Windows touch events and hands them to the TuioCursorServer
         to resend as TUIO messages on 3 channels: TUIO UDP on port 3333,
         TUIO UDP on port 3334, and Flash XML TCP on port 3000.
         Also intercepts all emulated mouse events and blocks them.
         
Windows 8 touch events:  WM_POINTERDOWN, WM_POINTERUPDATE WM_POINTERUP
Windows emulated mouse events (generated by touches):  LLMHF_INJECTED
*******************************************************************************/
/*
 Touch2Tuio - Windows 8 Touch to TUIO Bridge
 http://dm.tzi.de/research/hci/touch2tuio
 
 Copyright (c) 2010 Marc Herrlich and Benjamin Walther-Franks, 
 Research Group Digital Media, TZI, University of Bremen
 
 This program is free software; you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation; either version 2 of the License, or
 (at your option) any later version.
 
 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.
 
 You should have received a copy of the GNU General Public License
 along with this program; if not, write to the Free Software
 Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
*/
#pragma once

#include "targetver.h"
#define WINVER 0x0602
#define WIN32_LEAN_AND_MEAN  // Exclude rarely-used stuff from Windows headers.
#include <Windows.h>

// The following ifdef block is the standard way of creating macros which make
// exporting from a DLL simpler. All files within this DLL are compiled with 
// the TOUCHHOOK_EXPORTS symbol defined on the command line.  This symbol 
// should not be defined on any project that uses this DLL. This way any 
// other project whose source files include this file see TOUCHHOOK_API 
// functions as being imported from a DLL, whereas this DLL sees symbols
// defined with this macro as being exported.
#ifdef TOUCHHOOK_EXPORTS
#define TOUCHHOOK_API __declspec(dllexport)
#else
#define TOUCHHOOK_API __declspec(dllimport)
#endif

// Public API
TOUCHHOOK_API unsigned int UwmCustomPointerDown();
TOUCHHOOK_API unsigned int UwmCustomPointerUpdate();
TOUCHHOOK_API unsigned int UwmCustomPointerUp();
TOUCHHOOK_API unsigned int UwmCustomTouch();
TOUCHHOOK_API unsigned int UwmCustomTimer();

TOUCHHOOK_API void SetConsoleId( DWORD consoleId );
TOUCHHOOK_API bool InstallGlobalTouchHook();
TOUCHHOOK_API bool RemoveGlobalTouchHook();
